### PR TITLE
Update Python bulk download read-in example

### PR DESCRIPTION
**Pull request by OlivierBinette**
I consolidated the python examples in a single notebook and added automated testing for table URLs.

You can view the notebook here: https://github.com/PatentsView/PatentsView-Code-Snippets/blob/f0837f00ce3bee3aedb942410db687582277140f/03_bulk_download_read_in/Python%20Scripts/pandas_example.ipynb

### CODE REVIEW

**Comment by jbutler-air** [comment]
This looks great, Olivier!
I have a couple suggestions:
* add a docstring to the function that notes that the file is being read from the internet and that the function accepts the same kwargs as pd.read_csv
* can you modify the dtype specification so that certain fields (sequences in particular) are read as a numeric type instead of a string?
* this bit is more cosmetic, but I think the info portion at the bottom would be more readable presented in markdown than in json.

**Comment by OlivierBinette** [comment]
@jbutler-air Thanks for your comments! 

- I added a docstring to the function. 
- For the data schema, I'd recommend against parsing column types, unless we had a detailed schema specification to pull column types from. CSV files are strings and people can parse columns as needed. 
- For the sources file, it shows the structure of the `sources` dictionary object that is meant to be used programmatically. It's not meant to be a visual table; that's on the patentsview website.

**Comment by OlivierBinette** [comment]
I added a duckdb example: https://github.com/PatentsView/PatentsView-Code-Snippets/blob/66da72ca2b69369f6957d079916c77df920c9c32/03_bulk_download_read_in/Python%20Scripts/duckdb_example.ipynb

**Comment by OlivierBinette** [comment]
I looked through some of the other snippets folders and there's lots of legacy code or rather poor code. I suggest we clean it up and remove legacy code files.

**Comment by OlivierBinette** [comment]
Closing this PR for bigger rework

**Pull request closed without merging**
